/*
 * Copyright (C) 2011, Hans Marggraff and other copyright owners as documented in the project's IP log.
 * This program and the accompanying materials are made available under the terms of the Eclipse Distribution License v1.0 which accompanies this distribution, is reproduced below, and is available at http://www.eclipse.org/org/documents/edl-v10.php
 * All rights reserved.
 * Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
 * - Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
 * - Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
 * - Neither the name of the Eclipse Foundation, Inc. nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package org.funql.ri.sisql.test

import org.testng.annotations.Test
import org.funql.ri.parser.FqlParser
import org.funql.ri.test.genericobject.TypeDef
import org.funql.ri.test.genericobject.FieldDef
import org.testng.annotations.AfterClass
import java.util.ArrayList
import org.testng.Assert
import org.testng.Assert.assertEquals
import java.sql.ResultSet
import org.funql.ri.data.FqlDataException
import org.funql.ri.data.NamedValues
import org.funql.ri.test.cameradata.CameraData


/**
 * Unit test for simple Sql Driver.
 */
class HSqlUpdateTest : HSqlTestBase()
{
    val target: TypeDef = TypeDef("target", FieldDef.str("f"));

    {
        createTable(target, conn)
    }

    Test fun primaryKeys() {
        val meta = conn.getMetaData()!!
        val rs = meta.getPrimaryKeys(null, null, target.name.toUpperCase())!!

        val list = ArrayList<String>()
        while (rs.next()) {
            val columnName = rs.getString("COLUMN_NAME")!!
            list.add(columnName)
        }
        Assert.assertEquals(list[0], "ID")
    }
    Test fun generatedKeys() {
        val st = conn.createStatement()!!;
        st.executeUpdate("create table survey2 (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name varchar(32));");
        val pks = intArray(1)
        st.executeUpdate("insert into survey2 (name ) values ('nameValue')", pks);

        val generatedKeys: ResultSet? = st.getGeneratedKeys();

        if (null == generatedKeys || !generatedKeys.next())
            throw FqlDataException("Could not determine generated keys for insert")

        val ret = generatedKeys.getObject(1)!!;

        println(ret)
        Assert.assertEquals(ret, 0)
    }
    Test fun createKeys() {
        val st = conn.createStatement()!!;
        st.executeUpdate("create table survey (id INTEGER PRIMARY KEY,name varchar(32));");
        st.executeUpdate("create sequence survey_seq as integer;");
        val pks = intArray(1)
        st.executeUpdate("insert into survey (id, name ) values ( NEXT VALUE FOR survey_seq, 'nameValue')", pks);

        val generatedKeys: ResultSet? = st.getGeneratedKeys();

        if (null == generatedKeys || !generatedKeys.next())
            throw FqlDataException("Could not determine generated keys for insert")

        val ret = generatedKeys.getObject(1)!!;

        println(ret)
        Assert.assertEquals(ret, 0)
    }
    Test fun sequenceAccess() {
        val st = conn.createStatement()!!;
        st.executeUpdate("create table seqtest (id INTEGER PRIMARY KEY,name varchar(32));");
        st.executeUpdate("create sequence testseq as integer;");

        val ret = readAll("call NEXT VALUE FOR testseq")
        assertEquals(ret.values[0][0], 0)
    }

    Test fun toplevelInsert() {
        val iterator = run("into target put ID:33, f:'x'")
        val any = iterator.next()
        assertEquals((any as NamedValues).getValues()!![0], 33 as Long)
        val all = readAll("select * from ${target.name}")
        val strings = array("ID", "F")
        assertEquals(all.fields, strings)
        assertEquals(all.values.size(), 1)
        assertEquals(all.values[0], array(33 as Long, "x"))

    }


    Test(dependsOnMethods=array("toplevelInsert")) fun toplevelUpdate() {
        println("topLevelUpdate")
        val iterator = run("into target put ID:33, f:'y'")
        val any = iterator.next()
        assertEquals((any as NamedValues).getValues()!![0], 33 as Long)
        val all = readAll("select * from ${target.name}")
        val strings = array("ID", "F")
        assertEquals(all.fields, strings)
        assertEquals(all.values.size(), 1)
        assertEquals(all.values[0], array(33 as Long, "y"))
    }
    fun run(q: String) = FqlParser.runQuery(q, null, sisConn)!!

    AfterClass fun close() {
        conn.close()
    }


}
